### ISSUE TITLE
Consolidate duplicate `conda_build` keys in `conda-forge.yml`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyclesperanto-feedstock#21]
It looks like there are duplicate `conda_build` keys in `conda-forge.yml`

https://github.com/conda-forge/pyclesperanto-feedstock/blob/3dc80c8041a186497473b7dc055cccace2d8fef6/conda-forge.yml#L5-L6

https://github.com/conda-forge/pyclesperanto-feedstock/blob/3dc80c8041a186497473b7dc055cccace2d8fef6/conda-forge.yml#L11-L12

Would it be possible to consolidate this content under one `conda_build` key and drop the other?

This would help fix some issues the bot (used for migrations and version updates) is seeing

**Comment by StRigaud** [comment]
Thanks for pointing this!

**Comment by jakirkham** [comment]
> This would help fix some issues the bot (used for migrations and version updates) is seeing

...and only moments later the bot has a NumPy 2.0 migration PR: https://github.com/conda-forge/pyclesperanto-feedstock/pull/23 😉
